# coding: utf-8

from __future__ import absolute_import
from data_index.models.labels import Labels
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DataPointer(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, uri=None, individual_names=None, all_individuals=None, labels=None):
        """
        DataPointer - a model defined in Swagger

        :param name: The name of this DataPointer.
        :type name: str
        :param uri: The uri of this DataPointer.
        :type uri: str
        :param individual_names: The individual_names of this DataPointer.
        :type individual_names: List[str]
        :param all_individuals: The all_individuals of this DataPointer.
        :type all_individuals: bool
        :param labels: The labels of this DataPointer.
        :type labels: Labels
        """
        self.swagger_types = {
            'name': str,
            'uri': str,
            'individual_names': List[str],
            'all_individuals': bool,
            'labels': Labels
        }

        self.attribute_map = {
            'name': 'name',
            'uri': 'uri',
            'individual_names': 'individualNames',
            'all_individuals': 'allIndividuals',
            'labels': 'labels'
        }

        self._name = name
        self._uri = uri
        self._individual_names = individual_names
        self._all_individuals = all_individuals
        self._labels = labels

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataPointer of this DataPointer.
        :rtype: DataPointer
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self):
        """
        Gets the name of this DataPointer.
        Server generated unique resource name of the form 'datasets/*/dataPointers/*'. 

        :return: The name of this DataPointer.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this DataPointer.
        Server generated unique resource name of the form 'datasets/*/dataPointers/*'. 

        :param name: The name of this DataPointer.
        :type name: str
        """

        self._name = name

    @property
    def uri(self):
        """
        Gets the uri of this DataPointer.
        A URI for the data that this pointer represents, for example gs://bucket/object.txt or https://www.googleapis.com/bigquery/v2/projects/genomics-public-data/datasets/1000_genomes/tables. URIs must be unique within this dataset. 

        :return: The uri of this DataPointer.
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """
        Sets the uri of this DataPointer.
        A URI for the data that this pointer represents, for example gs://bucket/object.txt or https://www.googleapis.com/bigquery/v2/projects/genomics-public-data/datasets/1000_genomes/tables. URIs must be unique within this dataset. 

        :param uri: The uri of this DataPointer.
        :type uri: str
        """
        if uri is None:
            raise ValueError("Invalid value for `uri`, must not be `None`")

        self._uri = uri

    @property
    def individual_names(self):
        """
        Gets the individual_names of this DataPointer.
        One-of individualNames or allIndividuals; full individual names of the form 'datasets/*/individuals/*'. These individuals and this dataPointer must belong to the same dataset. 

        :return: The individual_names of this DataPointer.
        :rtype: List[str]
        """
        return self._individual_names

    @individual_names.setter
    def individual_names(self, individual_names):
        """
        Sets the individual_names of this DataPointer.
        One-of individualNames or allIndividuals; full individual names of the form 'datasets/*/individuals/*'. These individuals and this dataPointer must belong to the same dataset. 

        :param individual_names: The individual_names of this DataPointer.
        :type individual_names: List[str]
        """

        self._individual_names = individual_names

    @property
    def all_individuals(self):
        """
        Gets the all_individuals of this DataPointer.
        One-of individualNames or allIndividuals.

        :return: The all_individuals of this DataPointer.
        :rtype: bool
        """
        return self._all_individuals

    @all_individuals.setter
    def all_individuals(self, all_individuals):
        """
        Sets the all_individuals of this DataPointer.
        One-of individualNames or allIndividuals.

        :param all_individuals: The all_individuals of this DataPointer.
        :type all_individuals: bool
        """

        self._all_individuals = all_individuals

    @property
    def labels(self):
        """
        Gets the labels of this DataPointer.

        :return: The labels of this DataPointer.
        :rtype: Labels
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """
        Sets the labels of this DataPointer.

        :param labels: The labels of this DataPointer.
        :type labels: Labels
        """

        self._labels = labels

