# coding: utf-8

from __future__ import absolute_import
from data_index.models.labels import Labels
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Individual(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, labels=None):
        """
        Individual - a model defined in Swagger

        :param name: The name of this Individual.
        :type name: str
        :param labels: The labels of this Individual.
        :type labels: Labels
        """
        self.swagger_types = {
            'name': str,
            'labels': Labels
        }

        self.attribute_map = {
            'name': 'name',
            'labels': 'labels'
        }

        self._name = name
        self._labels = labels

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Individual of this Individual.
        :rtype: Individual
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self):
        """
        Gets the name of this Individual.
        Unique client-specified resource name of the individual of the form 'datasets/*/individuals/*'. 

        :return: The name of this Individual.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Individual.
        Unique client-specified resource name of the individual of the form 'datasets/*/individuals/*'. 

        :param name: The name of this Individual.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def labels(self):
        """
        Gets the labels of this Individual.

        :return: The labels of this Individual.
        :rtype: Labels
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """
        Sets the labels of this Individual.

        :param labels: The labels of this Individual.
        :type labels: Labels
        """

        self._labels = labels

