runtime: python
env: flex
entrypoint: gunicorn -b ":$PORT" -e FLASK_SETTINGS="/home/vmagent/app/dev.settings" data_index.__main__:app

runtime_config:
  python_version: 2

endpoints_api_service:
  name: "data-index.endpoints.bvdp-verily-dev.cloud.goog"
  config_id: "2017-07-20r0"
